'use strict';

// Reading the stamp that scripts/build-info.js leaves behind.
//
// Everything here is pure except `read`, so the formatting can be tested
// without Electron and without a packaged app — same split as src/cache.js.
//
// The file is absent in a source run (`npm start`, `node --test`), and that is
// a normal state rather than an error: an app running from the working tree has
// no single commit to claim. It says so instead of guessing.

const fs = require('node:fs');
const path = require('node:path');

// Ten hex digits. Seven is git's traditional abbreviation and GitHub's display
// width, but it is short enough to collide in a repo of any size, and this
// string's whole job is to identify one build unambiguously.
const SHORT_LENGTH = 10;

const UNKNOWN = { commit: null, shortCommit: null, branch: null, dirty: false, builtAt: null };

/**
 * Coerce whatever was on disk into the shape the rest of the app expects.
 *
 * Tolerant on purpose: this file is generated by a build hook, and a truncated
 * or hand-edited copy must degrade to "source build" rather than take the
 * settings page down with it.
 *
 * @param {unknown} raw
 * @returns {{commit: string|null, shortCommit: string|null, branch: string|null, dirty: boolean, builtAt: string|null}}
 */
function normalize(raw) {
  if (!raw || typeof raw !== 'object') return { ...UNKNOWN };
  // A commit is 40 hex characters. Anything else — a branch name, a truncated
  // write, a placeholder — is not one, and half a hash is worse than none.
  const commit = typeof raw.commit === 'string' && /^[0-9a-f]{40}$/i.test(raw.commit)
    ? raw.commit.toLowerCase()
    : null;
  return {
    commit,
    shortCommit: commit ? commit.slice(0, SHORT_LENGTH) : null,
    branch: typeof raw.branch === 'string' && raw.branch ? raw.branch : null,
    dirty: raw.dirty === true,
    builtAt: typeof raw.builtAt === 'string' && raw.builtAt ? raw.builtAt : null,
  };
}

/**
 * The stamp for this build, or the unknown shape when running from source.
 *
 * @param {string} [file]  Override, for tests.
 */
function read(file = path.join(__dirname, 'build-info.json')) {
  try {
    return normalize(JSON.parse(fs.readFileSync(file, 'utf8')));
  } catch {
    return { ...UNKNOWN };
  }
}

/** `2026-09-02T08:41:07Z` -> `2026-09-02 08:41Z`, or null for anything else. */
function formatBuiltAt(builtAt) {
  const match = /^(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2})/.exec(builtAt || '');
  return match ? `${match[1]} ${match[2]}Z` : null;
}

/**
 * The one-line identity shown in Settings.
 *
 * Reads as a parenthetical after the version, which is the part people quote:
 *
 *   1.0.0 (a1b2c3d4e5, built 2026-09-02 08:41Z)
 *   1.0.0 (fix-clicks a1b2c3d4e5, built 2026-09-02 08:41Z)
 *   1.0.0 (a1b2c3d4e5-dirty, built 2026-09-02 08:41Z)
 *   1.0.0 (source build)
 *
 * The branch is shown only when it is not `main`, because on `main` it is noise
 * and off it, it is the single most useful thing on the line.
 *
 * @param {string} version
 * @param {ReturnType<typeof normalize>} info
 */
function describe(version, info) {
  const stamp = normalize(info);
  if (!stamp.shortCommit) return `${version} (source build)`;

  const sha = stamp.dirty ? `${stamp.shortCommit}-dirty` : stamp.shortCommit;
  const named = stamp.branch && stamp.branch !== 'main' ? `${stamp.branch} ${sha}` : sha;
  const built = formatBuiltAt(stamp.builtAt);
  return `${version} (${named}${built ? `, built ${built}` : ''})`;
}

/**
 * A value identifying this build for the cache-clearing check, or null.
 *
 * Null for a dirty tree on purpose. Two different dirty builds of the same
 * commit share a hash, so trusting it there would stop detecting upgrades
 * during exactly the work most likely to need them; the caller falls back to
 * the bundle's size and mtime, which do move. See cache.buildFingerprint.
 */
function buildId(info) {
  const stamp = normalize(info);
  return stamp.commit && !stamp.dirty ? stamp.commit : null;
}

module.exports = { SHORT_LENGTH, normalize, read, describe, buildId, formatBuiltAt };
